version: '3.8'
services:
  database:
    image: 'mongo'
    container_name: 'mongo-sam' #just container name - can be anything
    environment:
      - MONGO_INITDB_ROOT_USERNAME:'root' # container image has these variables reffered to 
      - MONGO_INITDB_ROOT_PASSWORD:'rootpasswd' # container image has these variables reffered to 
    ports:
      - 27017:27017
    volumes:
      - container_database_space:/data/db # key is volume created on host and value is in the image
    networks:
      - fullstack-network
  dev_env:
    image: 'dev_pyhon_image'
    container_name: 'fullstack_dev_python'
    build: ./jupyter-notebook-docker
    networks:
      - fullstack-network
    ports:
      - 8888:8888
    volumes:
      - container_notebook_space:/home/jovyan # key is on the host and value is in the image

   
    
volumes: 
  container_database_space: # empty value since it is default. 
    external: true #if the directory is not there it will error
  container_notebook_space: 
    external: true 

networks:
  fullstack-network:
    driver: bridge
    name: fullstack-network




