# pull official base image
FROM python:3.8.1-slim-buster

# set work directory
WORKDIR /home/sampath/

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
EXPOSE 8888
# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . .

ENTRYPOINT ["python", "app.py"]
